In [2]:
from docplex.mp.model import Model
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import distance_matrix as dm
import pandas as pd
import os

TARGET_WEEKDAY = 0  # 0 = Monday, 1 = Tuesday, ..., 6 = Sunday
TARGET_HOUR = 8  # 0 = 00:00, 1 = 01:00, ..., 23 = 23:00

load_dotenv()

api_key = os.getenv("GOOGLE_MAPS_API_KEY")

matrix_time_first_tw, matrix_distance = dm.main(TARGET_WEEKDAY, TARGET_HOUR, api_key)
matrix_time_second_tw, matrix_distance = dm.main(
    TARGET_WEEKDAY, TARGET_HOUR + 1, api_key
)
matrix_time_third_tw, matrix_distance = dm.main(
    TARGET_WEEKDAY, TARGET_HOUR + 2, api_key
)
matrix_time_fourth_tw, matrix_distance = dm.main(
    TARGET_WEEKDAY, TARGET_HOUR + 3, api_key
)

print(matrix_time_first_tw)
print("\n\n")
print(matrix_time_second_tw)
print("\n\n")
print(matrix_time_third_tw)
print("\n\n")
print(matrix_time_fourth_tw)
print("\n\n")
print(matrix_distance)

# sava datas in a matrix of matrixes
first_data = matrix_time_first_tw
second_data = matrix_time_second_tw
third_data = matrix_time_third_tw
fourth_data = matrix_time_fourth_tw

data = [first_data, second_data, third_data, fourth_data]

# parameters for time model
c = 20  # number of nodes
d = [8, 9, 10, 11, 12]  # time intervals
tw = [
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
]  # time windows
q = [
    0,
    10,
    10,
    -10,
    10,
    10,
    -10,
    10,
    10,
    -10,
    10,
    10,
    10,
    -10,
    10,
    10,
    10,
    10,
    -10,
    10,
]  # quantity of goods to collect/deliver
Q = 500  # maximum capacity of the vehicle
t_mv = 0.5  # time to move one item in/out from a vehicle [min]
M = 100000  # big M
tot_q = 0  # total quantity of goods to collect/delivery
del_q = 0  # quantity of goods to deliver
v = 20
for good in q:
    tot_q += abs(good)

tot_t_mv = tot_q * t_mv

print("Total time required to collect/deliver all goods:", tot_t_mv, "minutes")

for good in q:
    if good < 0:
        del_q += good
del_q = abs(del_q)

print(f"Computing for {v} vehicles")

# define model
mdl = Model("CVRP")
mdl.parameters.timelimit = 60

# decision variables

x = mdl.binary_var_dict(
    (
        (i, j, t, k)
        for i in range(c)
        for j in range(c)
        for t in range(len(d) - 1)
        for k in range(v)
    ),
    name="x",
)  # x == 1 if it is true that we are going from node i to node j at time t with vehicle k
T = mdl.continuous_var_matrix(
    c + 1, v, name="t"
)  # arrival time at node i for vehicle k
C = mdl.continuous_var_matrix(
    c, v, name="C"
)  # quantity of goods when you leave node i for vehicle k

# nodes constraints
for k in range(v):
    mdl.add_constraint(
        mdl.sum(mdl.sum(x[0, j, t, k] for j in range(1, c)) for t in range(len(d) - 1))
        <= 1  # TO CHANGE FROM ==(it was a test to make boot vehicle works) to <=
    )  # every vehicle must leave the depot exactly once, hence every vehicle is expoloited

for k in range(v):
    mdl.add_constraint(
        mdl.sum(mdl.sum(x[j, 0, t, k] for j in range(1, c)) for t in range(len(d) - 1))
        == mdl.sum(
            mdl.sum(x[0, j, t, k] for j in range(1, c)) for t in range(len(d) - 1)
        )
    )  # every vehicle that has left the depot must return to it

for j in range(1, c):
    mdl.add_constraint(
        mdl.sum(
            mdl.sum(
                mdl.sum(x[i, j, t, k] for i in range(c) if i != j)
                for t in range(len(d) - 1)
            )
            for k in range(v)
        )
        == 1
    )  # every node must be visited exactly once

for k in range(v):
    for j in range(1, c):
        mdl.add_constraint(
            mdl.sum(
                mdl.sum(x[i, j, t, k] for i in range(c) if i != j)
                for t in range(len(d) - 1)
            )
            == mdl.sum(
                mdl.sum(x[j, i, t, k] for i in range(c) if i != j)
                for t in range(len(d) - 1)
            )
        )  # when you visit a node you ought to leave it

# time
for k in range(v):
    for t in range(len(d) - 1):
        mdl.add_constraint(
            T[0, k] >= d[t] * 60 * mdl.sum(x[0, j, t, k] for j in range(1, c))
        )  # when you leave depot at a time t, you ought to leave it at that time

for k in range(v):
    for t in range(len(d) - 1):
        for j in range(1, c):
            mdl.add_constraint(
                T[j, k] >= d[t] * 60 * mdl.sum(x[i, j, t, k] for i in range(1, c))
            )  # when you arrive at a node j from node i at time t, you ought to arrive at that time

for k in range(v):
    for t in range(len(d) - 1):
        for j in range(1, c):
            mdl.add_constraint(
                T[j, k]
                <= d[t + 1] * 60 + (1 - mdl.sum(x[i, j, t, k] for i in range(1, c))) * M
            )  # when arrive in j from i at time t, you ought to reach it before the end of the time interval

for k in range(v):
    for t in range(len(d) - 1):
        for i in range(1, c):
            mdl.add_constraint(
                T[i, k] >= d[t] * 60 * mdl.sum(x[i, j, t, k] for j in range(0, c))
            )  # when you arrive at node j from node i at time t, you ought to depart in that time interval

for k in range(v):
    for t in range(len(d) - 1):
        for i in range(1, c):
            mdl.add_constraint(
                T[i, k]
                <= d[t + 1] * 60 + (1 - mdl.sum(x[i, j, t, k] for j in range(0, c))) * M
            )  # when you arrive in j from i at time t, you ought to depart from i after the start of that time interval

for k in range(v):
    for i in range(c):
        for j in range(1, c):
            for t in range(len(d) - 1):
                if i != j:
                    mdl.add_constraint(
                        (1 - x[i, j, t, k]) * M + T[j, k] - T[i, k]
                        >= data[t][i][j] + t_mv * abs(q[j])
                    )
                    mdl.add_constraint(
                        (1 - x[i, j, t, k]) * M - T[j, k] + T[i, k]
                        >= -data[t][i][j] - t_mv * abs(q[j])
                    )  # if you go from i to j, then the difference between the arrival time at j and i should be the same as the time required to go from i to j
                    # plus the time to load/unload the required goods

for k in range(v):
    for t in range(len(d) - 1):
        for i in range(1, c):
            mdl.add_constraint(
                (1 - x[i, 0, t, k]) * M + T[c, k] - T[i, k] >= data[t][i][0]
            )
            mdl.add_constraint(
                (1 - x[i, 0, t, k]) * M - T[c, k] + T[i, k] >= -data[t][i][0]
            )  # if you go from i to the depot, then the difference between the arrival time at the depot and i should be the same as the time required to go
            # from i to the depot

for k in range(v):
    for i in range(1, c):
        mdl.add_constraint(
            tw[i - 1][0] * 60 <= T[i, k]
        )  # you must arrive in i on-time (based on client side) lowest limit
        mdl.add_constraint(
            T[i, k] <= tw[i - 1][1] * 60
        )  # you must arrive in i on-time (based on client side) upper limit

for k in range(v):
    mdl.add_constraint(
        T[c, k] - T[0, k] <= 8 * 60
    )  # you must return to the depot within 8 hours (a shift)

# quantity constraints
for k in range(v):
    for t in range(len(d) - 1):
        for i in range(c):
            for j in range(1, c):
                if i != j:
                    mdl.add_constraint(
                        C[i, k] - C[j, k] + q[j] <= (1 - x[i, j, t, k]) * M
                    )
                    mdl.add_constraint(
                        C[j, k] - C[i, k] - q[j] <= (1 - x[i, j, t, k]) * M
                    )  # if you go from i to j, then the difference between the quantity of goods at i and j should be the same as the quantity
                    # of goods to deliver at j

for k in range(v):
    for i in range(c):
        mdl.add_constraint(
            max(0, q[i]) <= C[i, k]
        )  # if node i requires to load goods, you must leave i with at least the quantity of goods to collect
        mdl.add_constraint(
            C[i, k] <= min(Q, Q + q[i])
        )  # you must leave i with at most Q+q[i] goods if you have to deliver at node i goods or Q if you have to collect goods at node i

for k in range(v):
    del_qi = 0
    for j in range(1, c):
        if q[j] < 0:
            del_qi += q[j] * mdl.sum(
                mdl.sum(x[i, j, t, k] for i in range(c)) for t in range(len(d) - 1)
            )
    mdl.add_constraint(
        C[0, k] >= del_qi
    )  # each vehicle must depart from the depot with at least the quantity of goods to deliver for its route

# objective function
mdl.minimize(
    mdl.sum(
        mdl.sum(
            mdl.sum(
                mdl.sum(x[i, j, t, k] * data[t][i][j] for i in range(c))
                for j in range(c)
            )
            for t in range(len(d) - 1)
        )
        for k in range(v)
    )
)  # minimize time of routes

sol = mdl.solve()

if sol is None:
    print("No solution found")

print("\n\n\nTotal time required is:")

print(sol.objective_value)

print(sol.objective_value + tot_t_mv)

print("\n\n\n")


counter_vehicles=0
for k in range(v):
    counter_routes=0
    for t in range(len(d)-1):
        for i in range(c):
            for j in range(c):
                 counter_routes+= sol.get_value(x[i, j, t, k])
    if counter_routes==0 :
        print(f"vehicle {k} is NOT used")
    else:
        print(f"vehicle {k} is used")
        counter_vehicles+=1

print(f"Total number of used vehicles: {counter_vehicles}")

Loading time matrix from file...
Loading time matrix from file...
Loading time matrix from file...
Loading time matrix from file...
[[ 0.   19.83 17.05 19.62 23.92 22.42 12.47 20.5  12.47 21.32 21.98 22.3
  22.58  5.62 28.78  9.45 13.38 31.75 10.65 12.58  9.23  8.15  3.9  10.85
   8.5 ]
 [ 9.43  0.   11.13 13.62 18.42 16.82 15.68 26.9  11.3  23.18 17.   18.3
  17.07  9.87 24.17 15.05 13.78 29.88 14.68 12.8  13.48  5.6   6.92 10.83
   2.48]
 [24.72 19.32  0.    8.93  7.77  5.98 28.52 40.87 22.82 11.35  5.35 10.15
   6.33 21.8  12.95 28.87 24.05 18.22 20.22 23.03 18.92 25.57 24.67 22.33
  23.63]
 [20.77 12.87  5.97  0.    4.92  5.15 21.28 37.35 16.93 14.62 11.83 12.98
   3.52 19.3  12.45 25.72 19.68 17.75 13.82 18.73 12.57 17.12 18.2  16.92
  15.02]
 [19.07 29.78 26.97 28.25  0.   26.37 28.88 34.62 25.52 17.1  27.15 28.68
  26.52 16.08 24.05 22.93 28.05 26.92 17.98 27.18 16.77 19.97 19.83 24.92
  18.32]
 [21.   13.13  6.2   3.32  5.23  0.   21.33 37.98 17.25 14.85 11.97 13.15
   3.82 20.

DOcplexLimitsExceeded: **** Promotional version. Problem size limits (1000 vars, 1000 consts) exceeded, model has 1263 vars, 4710 consts, CPLEX code=1016

In [50]:
from docplex.mp.model import Model
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import distance_matrix as dm
import pandas as pd
import os

TARGET_WEEKDAY = 0  # 0 = Monday, 1 = Tuesday, ..., 6 = Sunday
TARGET_HOUR = 8  # 0 = 00:00, 1 = 01:00, ..., 23 = 23:00

load_dotenv()

api_key = os.getenv("GOOGLE_MAPS_API_KEY")

matrix_times, matrix_distance = dm.main(TARGET_WEEKDAY, TARGET_HOUR, api_key)

# parameters for time model
c = 4  # number of nodes
q = [0, -10, 10, -10]  # quantity of goods to collect/deliver
Q = 100  # maximum capacity of the vehicle
distances = matrix_distance  # should match value of c
A = [(i, j) for i in range(c) for j in range(c) if i != j]
N0 = list(range(1, c))  # Nodi clienti (escluso il deposito)
L = 100  # Capacità massima della batteria
a = {(i, j): 2 for (i, j) in A}  # Consumo base per arco
b = 0.5  # Consumo dipendente dal carico
c_E = 1  # Costo per unità di energia consumata
c_F = 1  # Costo fisso per veicolo
c_M = 1  # Costo per unità di distanza

del_q = 0  # quantity of goods to deliver

M = 100000  # big M

v = 2  # Number of vehicles

for i in range(len(distances)):
    for j in range(len(distances)):
        distances[i][j] = distances[i][j] / 1000  # Convert meters to kilometers

for good in q:
    if good < 0:
        del_q += good
del_q = -del_q

print("Total goods to deliver:", del_q)

mdl_energy = Model("EnergyOptimization")

# Variabili di decisione

x_energy = mdl_energy.binary_var_cube(
    len(distances), len(distances), v, name="x"
)  # Percorsi
C = mdl_energy.continuous_var_matrix(
    range(c), range(v), name="C"
)  # quantity of goods when you leave node i for vehicle k
w = mdl_energy.continuous_var_list(v, name="w")  # Consumo massimo di energia

# Funzione obiettivo: Minimizzare i costi energetici

mdl_energy.minimize(
    mdl_energy.sum(
        [
            mdl_energy.sum([c_F * x_energy[0, j, k] for j in range(1, len(distances))])
            + mdl_energy.sum([c_M * distances[i][j] * x_energy[i, j, k] for i, j in A])
            + c_E * w[k]
            for k in range(v)
        ]
    )
)

# Vincoli
for k in range(v):
    mdl_energy.add_constraint(mdl_energy.sum(x_energy[0, j, k] for j in N0) == 1)

for i in N0:
    mdl_energy.add_constraint(
        mdl_energy.sum(x_energy[i, j, k] for k in range(v) for j in range(c) if j != i)
        == 1
    )

for k in range(v):
    mdl_energy.add_constraint(
        mdl_energy.sum(x_energy[j, 0, k] for j in range(1, c))
        == mdl_energy.sum(x_energy[0, j, k] for j in range(1, c))
    )  # every vehicle that has left the depot must return to it

for i in range(len(distances)):
    for k in range(v):
        mdl_energy.add_constraint(
            mdl_energy.sum(x_energy[j, i, k] for j in range(len(distances)) if j != i)
            == mdl_energy.sum(
                x_energy[i, j, k] for j in range(len(distances)) if j != i
            )
        )

# quantity constraints
for k in range(v):
    for i in range(c):
        for j in range(1, c):
            if i != j:
                mdl_energy.add_constraint(
                    C[i, k] - C[j, k] + q[j] <= (1 - x_energy[i, j, k]) * M
                )
                mdl_energy.add_constraint(
                    C[j, k] - C[i, k] - q[j] <= (1 - x_energy[i, j, k]) * M
                )  # if you go from i to j, then the difference between the quantity of goods at i and j should be the same as the quantity
                # of goods to deliver at j

for k in range(v):
    for i in range(c):
        mdl_energy.add_constraint(
            max(0, q[i]) <= C[i, k]
        )  # if node i requires to load goods, you must leave i with at least the quantity of goods to collect
        mdl_energy.add_constraint(
            C[i, k] <= min(Q, Q + q[i])
        )  # you must leave i with at most Q+q[i] goods if you have to deliver at node i goods or Q if you have to collect goods at node i

for k in range(v):
    del_qi = 0
    for j in range(1, c):
        if q[j] < 0:
            del_qi += q[j] * mdl_energy.sum(x_energy[i, j, k] for i in range(c))
    print(del_qi)
    mdl_energy.add_constraint(
        C[0, k] >= -del_qi
    )  # each vehicle must depart from the depot with at least the quantity of goods to deliver for its route

for k in range(v):
    for row, col in A:
        mdl_energy.add_constraint(
            mdl_energy.sum(a[i, j] * x_energy[i, j, k] for i, j in A)
            + mdl_energy.sum(b * C[i, k] for i in range(c))
            <= w[k]
        )

for k in range(v):
    mdl_energy.add_constraint(0 <= w[k])
    mdl_energy.add_constraint(w[k] <= L)

# Risoluzione del modello

solution = mdl_energy.solve(log_output=False)

cost = solution.objective_value

if solution is None:
    print("Il modello non ha soluzione")
else:
    print("Costo totale:", solution.objective_value)
    for k in range(v):
        print(
            f"Consumo massimo del veicolo {k}: {solution.get_value(mdl_energy.get_var_by_name(f'w_{k}'))}"
        )

w = solution.get_values(w)

for w in w:
    if w == 0:
        unused_vehicle = True
        print("\nEsistono uno o più veicoli che non vengono utilizzati")
        break

for k in range(v):
    for i in range(c):
        for j in range(c):
            if solution.get_value(x_energy[i, j, k]) == 1:
                print(
                    f"Veicolo {k} va da {i} a {j} con un carico di {solution.get_value(C[i, k])} kg"
                )

Loading time matrix from file...
Total goods to deliver: 20
-10x_0_1_0-10x_0_3_0-10x_1_1_0-10x_1_3_0-10x_2_1_0-10x_2_3_0-10x_3_1_0-10x_3_3_0
-10x_0_1_1-10x_0_3_1-10x_1_1_1-10x_1_3_1-10x_2_1_1-10x_2_3_1-10x_3_1_1-10x_3_3_1
Costo totale: 48.972
Consumo massimo del veicolo 0: 16.0
Consumo massimo del veicolo 1: 14.0
Veicolo 0 va da 0 a 3 con un carico di 10.0 kg
Veicolo 0 va da 2 a 0 con un carico di 10.0 kg
Veicolo 0 va da 3 a 2 con un carico di 0 kg
Veicolo 1 va da 0 a 1 con un carico di 10.0 kg
Veicolo 1 va da 1 a 0 con un carico di 0 kg


In [97]:
from docplex.mp.model import Model
from dotenv import load_dotenv
import matplotlib.pyplot as plt
import distance_matrix as dm
import numpy as np
import pandas as pd
import os

TARGET_WEEKDAY = 0  # 0 = Monday, 1 = Tuesday, ..., 6 = Sunday
TARGET_HOUR = 8  # 0 = 00:00, 1 = 01:00, ..., 23 = 23:00

load_dotenv()

api_key = os.getenv("GOOGLE_MAPS_API_KEY")

matrix_time_first_tw, matrix_distance = dm.main(TARGET_WEEKDAY, TARGET_HOUR, api_key)
matrix_time_second_tw, matrix_distance = dm.main(
    TARGET_WEEKDAY, TARGET_HOUR + 1, api_key
)
matrix_time_third_tw, matrix_distance = dm.main(
    TARGET_WEEKDAY, TARGET_HOUR + 2, api_key
)
matrix_time_fourth_tw, matrix_distance = dm.main(
    TARGET_WEEKDAY, TARGET_HOUR + 3, api_key
)


# sava datas in a matrix of matrixes
first_data = matrix_time_first_tw
second_data = matrix_time_second_tw
third_data = matrix_time_third_tw
fourth_data = matrix_time_fourth_tw
data = [first_data, second_data, third_data, fourth_data]

# parameters for time model
c = 20  # number of nodes
d = [8, 9, 10, 11, 12]  # time intervals
tw = [
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
    [8, 12],
]  # time windows
q = [
    0,
    10,
    10,
    -10,
    10,
    10,
    -10,
    10,
    10,
    -10,
    10,
    10,
    10,
    -10,
    10,
    10,
    10,
    10,
    -10,
    10,
]  # quantity of goods to collect/deliver
Q = 500  # maximum capacity of the vehicle
t_mv = 0.5  # time to move one item in/out from a vehicle [min]
M = 100000  # big M
tot_q = 0  # total quantity of goods to collect/delivery
del_q = 0  # quantity of goods to deliver
v = 5
# parameters for energy model
distances = matrix_distance  # should match value of c
print(distances)
A = [(i, j) for i in range(c) for j in range(c) if i != j]
N0 = list(range(1, c))  # Nodi clienti (escluso il deposito)
L = 1000  # Capacità massima della batteria
a = {(i, j): 2 for (i, j) in A}  # Consumo base per arco
b = {(i, j): 0.5 for (i, j) in A}  # Consumo dipendente dal carico
b = 0.5
c_E = 1  # Costo per unità di energia consumata
c_F = 1  # Costo fisso per veicolo
c_M = 1  # Costo per unità di distanza

unused_vehicle = False

for good in q:
    tot_q += abs(good)

tot_t_mv = tot_q * t_mv

print("Total time required to collect/deliver all goods:", tot_t_mv, "minutes")

for good in q:
    if good < 0:
        del_q += good
del_q = abs(del_q)

print(f"Computing for {v} vehicles")

# define model
mdl = Model("Pareto")

# decision variables of time model

x = mdl.binary_var_dict(
    (
        (i, j, t, k)
        for i in range(c)
        for j in range(c)
        for t in range(len(d) - 1)
        for k in range(v)
    ),
    name="x",
)  # x == 1 if it is true that we are going from node i to node j at time t with vehicle k
T = mdl.continuous_var_matrix(
    c + 1, v, name="t"
)  # arrival time at node i for vehicle k
C = mdl.continuous_var_matrix(
    c, v, name="C"
)  # quantity of goods when you leave node i for vehicle k

# decison variables of energy model

x_energy = [[[ 0 for _ in range(v)] for _ in range(c)] for _ in range(c)]

for k in range(v):
    for i in range(c):
        for j in range(c):
            for t in range(len(d)-1):
                x_energy[i][j][k] += x[i, j, t, k] 


w = mdl.continuous_var_list(v, name="w")  # max consuption of energy

#contraints of time model
# nodes constraints
for k in range(v):
    mdl.add_constraint(
        mdl.sum(mdl.sum(x[0, j, t, k] for j in range(1, c)) for t in range(len(d) - 1))
        == 1  
    )  # every vehicle must leave the depot exactly once, hence every vehicle is expoloited

for k in range(v):
    mdl.add_constraint(
        mdl.sum(mdl.sum(x[j, 0, t, k] for j in range(1, c)) for t in range(len(d) - 1))
        == 1
    )  # every vehicle that has left the depot must return to it

for j in range(1, c):
    mdl.add_constraint(
        mdl.sum(
            mdl.sum(
                mdl.sum(x[i, j, t, k] for i in range(c) if i != j)
                for t in range(len(d) - 1)
            )
            for k in range(v)
        )
        == 1
    )  # every node must be visited exactly once

for k in range(v):
    for j in range(1, c):
        mdl.add_constraint(
            mdl.sum(
                mdl.sum(x[i, j, t, k] for i in range(c) if i != j)
                for t in range(len(d) - 1)
            )
            == mdl.sum(
                mdl.sum(x[j, i, t, k] for i in range(c) if i != j)
                for t in range(len(d) - 1)
            )
        )  # when you visit a node you ought to leave it

# time
for k in range(v):
    for t in range(len(d) - 1):
        mdl.add_constraint(
            T[0, k] >= d[t] * 60 * mdl.sum(x[0, j, t, k] for j in range(1, c))
        )  # when you leave depot at a time t, you ought to leave it at that time

for k in range(v):
    for t in range(len(d) - 1):
        for j in range(1, c):
            mdl.add_constraint(
                T[j, k] >= d[t] * 60 * mdl.sum(x[i, j, t, k] for i in range(1, c))
            )  # when you arrive at a node j from node i at time t, you ought to arrive at that time

for k in range(v):
    for t in range(len(d) - 1):
        for j in range(1, c):
            mdl.add_constraint(
                T[j, k]
                <= d[t + 1] * 60 + (1 - mdl.sum(x[i, j, t, k] for i in range(1, c))) * M
            )  # when arrive in j from i at time t, you ought to reach it before the end of the time interval

for k in range(v):
    for t in range(len(d) - 1):
        for i in range(1, c):
            mdl.add_constraint(
                T[i, k] >= d[t] * 60 * mdl.sum(x[i, j, t, k] for j in range(0, c))
            )  # when you arrive at node j from node i at time t, you ought to depart in that time interval

for k in range(v):
    for t in range(len(d) - 1):
        for i in range(1, c):
            mdl.add_constraint(
                T[i, k]
                <= d[t + 1] * 60 + (1 - mdl.sum(x[i, j, t, k] for j in range(0, c))) * M
            )  # when you arrive in j from i at time t, you ought to depart from i after the start of that time interval

for k in range(v):
    for i in range(c):
        for j in range(1, c):
            for t in range(len(d) - 1):
                if i != j:
                    mdl.add_constraint(
                        (1 - x[i, j, t, k]) * M + T[j, k] - T[i, k]
                        >= data[t][i][j] + t_mv * abs(q[j])
                    )
                    mdl.add_constraint(
                        (1 - x[i, j, t, k]) * M - T[j, k] + T[i, k]
                        >= -data[t][i][j] - t_mv * abs(q[j])
                    )  # if you go from i to j, then the difference between the arrival time at j and i should be the same as the time required to go from i to j
                    # plus the time to load/unload the required goods

for k in range(v):
    for t in range(len(d) - 1):
        for i in range(1, c):
            mdl.add_constraint(
                (1 - x[i, 0, t, k]) * M + T[c, k] - T[i, k] >= data[t][i][0]
            )
            mdl.add_constraint(
                (1 - x[i, 0, t, k]) * M - T[c, k] + T[i, k] >= -data[t][i][0]
            )  # if you go from i to the depot, then the difference between the arrival time at the depot and i should be the same as the time required to go
            # from i to the depot

for k in range(v):
    for i in range(1, c):
        mdl.add_constraint(
            tw[i - 1][0] * 60 <= T[i, k]
        )  # you must arrive in i on-time (based on client side) lowest limit
        mdl.add_constraint(
            T[i, k] <= tw[i - 1][1] * 60
        )  # you must arrive in i on-time (based on client side) upper limit

for k in range(v):
    mdl.add_constraint(
        T[c, k] - T[0, k] <= 8 * 60
    )  # you must return to the depot within 8 hours (a shift)

# quantity constraints
for k in range(v):
    for t in range(len(d) - 1):
        for i in range(c):
            for j in range(1, c):
                if i != j:
                    mdl.add_constraint(
                        C[i, k] - C[j, k] + q[j] <= (1 - x[i, j, t, k]) * M
                    )
                    mdl.add_constraint(
                        C[j, k] - C[i, k] - q[j] <= (1 - x[i, j, t, k]) * M
                    )  # if you go from i to j, then the difference between the quantity of goods at i and j should be the same as the quantity
                    # of goods to deliver at j

for k in range(v):
    for i in range(c):
        mdl.add_constraint(
            max(0, q[i]) <= C[i, k]
        )  # if node i requires to load goods, you must leave i with at least the quantity of goods to collect
        mdl.add_constraint(
            C[i, k] <= min(Q, Q + q[i])
        )  # you must leave i with at most Q+q[i] goods if you have to deliver at node i goods or Q if you have to collect goods at node i

for k in range(v):
    del_qi = 0
    for j in range(1, c):
        if q[j] < 0:
            del_qi += q[j] * mdl.sum(
                mdl.sum(x[i, j, t, k] for i in range(c)) for t in range(len(d) - 1)
            )
    mdl.add_constraint(
        C[0, k] >= -del_qi
    )  # each vehicle must depart from the depot with at least the quantity of goods to deliver for its route

# Convert meters to kilometers

for i in range(len(distances)):
    for j in range(len(distances)):
        distances[i][j] = distances[i][j] / 1000 


# Variabili di decisione energia

x_energy = [[[0 for _ in range(v)] for _ in range(c)] for _ in range(c)]

for k in range(v):
    for i in range(c):
        for j in range(c):
            for t in range(len(d) - 1):
                x_energy[i][j][k] += x[i, j, t, k]


w = mdl.continuous_var_list(v, name="w")  # Consumo massimo di energia
mdl.parameters.timelimit = 30
# Funzione obiettivo: Minimizzare i costi energetici

mdl_energy.minimize(
    mdl_energy.sum(
        [
            mdl_energy.sum([c_F * x_energy[0, j, k] for j in range(1, len(distances))])
            + mdl_energy.sum([c_M * distances[i][j] * x_energy[i, j, k] for i, j in A])
            + c_E * w[k]
            for k in range(v)
        ]
    )
)

# Vincoli
for k in range(v):
    mdl_energy.add_constraint(mdl_energy.sum(x_energy[0, j, k] for j in N0) <= 1)

for i in N0:
    mdl_energy.add_constraint(
        mdl_energy.sum(
            x_energy[i, j, k] for k in range(v) for j in range(len(distances)) if j != i
        )
        == 1
    )

for i in range(len(distances)):
    mdl_energy.add_constraint(
        mdl_energy.sum(x_energy[j, i, k] for j in range(len(distances)) if j != i)
        == mdl_energy.sum(x_energy[i, j, k] for j in range(len(distances)) if j != i)
    )

# quantity constraints
for k in range(v):
    for row, col in A:
        mdl.add_constraint(
            mdl.sum(a[i, j] * x_energy[i][j][k] for i, j in A)
            + mdl.sum(b * C[i, k] for i in range(c))
            <= w[k]
        )

for k in range(v):
    mdl_energy.add_constraint(0 <= w[k])
    mdl_energy.add_constraint(w[k] <= L)

# Risoluzione del modello

solution = mdl_energy.solve(log_output=False)

x_energy_result = [[[0 for _ in range(v)] for _ in range(c)] for _ in range(c)]
for k in range(v):
    for i in range(c):
        for j in range(c):
            for t in range(len(d) - 1):
                x_energy_result[i][j][k] += solution.get_value(x[i, j, t, k])
            print(x_energy_result[i][j][k], end=",")
        print()
    print("\n\n")
cost = solution.objective_value

if solution is None:
    print("Il modello non ha soluzione")
else:
    print("Costo totale:", solution.objective_value)
    for k in range(v):
        print(
            f"Consumo massimo del veicolo {k}: {solution.get_value(mdl_energy.get_var_by_name(f'w_{k}'))}"
        )

w = solution.get_values(w)

for w in w:
    if w == 0:
        unused_vehicle = True
        print("\nEsistono uno o più veicoli che non vengono utilizzati")
        break

for k in range(v):
    for i in range(c):
        # if solution.get_value(C[i,k])!=0:
        print(f"C[{i},{k}]:{solution.get_value(C[i,k])}")

Loading time matrix from file...
Creating a new time matrix...
API Call
Creating a new time matrix...
API Call
Creating a new time matrix...
API Call
[[ 0.   19.83 17.05]
 [ 9.43  0.   11.13]
 [24.72 19.32  0.  ]]

a:  0.25
w:  [159.0, 169.0, 132.0, 79.0, 79.0]

a:  0.5
w:  [116.99999999899956, 109.99999999999997, 132.0, 78.99999999999999, 99.99999999999996]

[[ 0.   20.63 17.22]
 [ 9.78  0.   10.87]
 [24.83 19.57  0.  ]]



[[ 0.   19.23 16.38]
 [ 9.65  0.   10.52]
 [21.3  17.42  0.  ]]



[[ 0.   19.23 16.2 ]
 [ 9.48  0.   10.7 ]
 [19.95 16.52  0.  ]]



[[   0. 3448. 3279.]
 [2219.    0. 2048.]
 [5046. 3542.    0.]]
[[   0. 3448. 3279.]
 [2219.    0. 2048.]
 [5046. 3542.    0.]]
Total time required to collect/deliver all goods: 80.0 minutes
Computing for 3 vehicles


IndexError: index 3 is out of bounds for axis 0 with size 3